### ISSUE TITLE
Useful error messages during macro expansion

### ISSUE THREAD

**Issue by JAremko** [jeaye/orchestra#39] opened 2019-01-30 19:00 UTC
When I refactor old code to use `defn-spec` instead of `defn` I sometimes forget to add return value specs. 
``` clojure
(defn-spec foo
  "I'm foo"
  [bar any?]
  bar)
```
It results in this "useless" error message:
```
 Unhandled java.lang.IllegalArgumentException
 find not supported on type: clojure.lang.Keyword
```

**It can be helpful (especially for beginners) if the error message was more precise.**

**Comment by jeaye** [comment] 2019-01-30 19:02
You're absolutely right, @JAremko. This is indeed a problem. However, since this is a duplicate of #36, I'm going to close it. You're welcome to subscribe to that thread, to know when this is fixed.

My goal is to fix this with spec, just as Clojure has done. Thanks for using Orchestra and reporting your concerns!

**Closed by jeaye** 2019-01-30 19:02 UTC
