### ISSUE TITLE
Lumo compatibility

### ISSUE THREAD

**Issue by arichiardi** [jeaye/orchestra#11] opened 2017-10-27 19:51 UTC
Hello @jeaye!

I am trying to get `orchestra` working within `lumo` and I am getting this error:

```
Started watching.
File changed: /home/arichiardi/git/cqrs-cljs/test/cqrs_cljs/scrutinizer_test.cljs
                                              ⬆
WARNING: Use of undeclared Var orchestra-cljs.spec.test$macros/eval at line 112 orchestra_cljs/spec/test.cljc
                                              ⬆
WARNING: Use of undeclared Var orchestra-cljs.spec.test$macros/eval at line 135 orchestra_cljs/spec/test.cljc
```

I think it is just a matter of setting the macro namespaces right for bootstrap consumption, which can be quickly achieved with [macrovich](https://github.com/cgrand/macrovich) or done manually. Hopefully I can look into this soon. I really like `orchestra` and I now want to use it everywhere :smile: 

_EDIT_: it actually seems more complicated then above proposed solution.

Thanks a lot for this library!

**Comment by danielcompton** [comment] 2017-10-29 20:34
Dupe of #10

**Comment by jeaye** [comment] 2017-10-29 21:19
Indeed, this is a dupe of #10. Thanks for the great report, @arichiardi, and I'm glad you're enjoying Orchestra. I'm gonna close this, but feel free to jump into the conversation on #10.

Thanks @danielcompton :)

**Closed by jeaye** 2017-10-29 21:19 UTC
